# Generated by Django 2.2.9 on 2020-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recuirtmentModel',
            fields=[
                ('oppertunitycode', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=30)),
                ('startregistration', models.DateField()),
                ('agelimit', models.IntegerField()),
                ('lastregistration', models.IntegerField()),
                ('departmentid', models.CharField(max_length=10)),
                ('positions', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('responsibilities', models.CharField(max_length=250)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
