# Generated by Django 2.2.9 on 2020-02-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuirtmentmodel',
            name='lastregistration',
            field=models.DateField(),
        ),
    ]
