# Generated by Django 2.2.9 on 2020-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200217_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSeheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantId', models.IntegerField()),
                ('employeeId', models.IntegerField()),
                ('scheduleDate', models.DateField()),
            ],
        ),
    ]
